# Generated by Django 3.2.9 on 2021-11-12 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='photo/%y/%m/%d')),
                ('Categories', models.ManyToManyField(to='pin.Category')),
                ('casts', models.ManyToManyField(to='pin.Cast')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('commondata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pin.commondata')),
                ('running_time', models.IntegerField()),
            ],
            bases=('pin.commondata',),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('commondata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pin.commondata')),
                ('eps_number', models.IntegerField()),
            ],
            bases=('pin.commondata',),
        ),
    ]
